# Generated by Django 5.1.1 on 2024-11-22 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_intake', models.DateField()),
                ('email_address', models.EmailField(max_length=254)),
                ('home_address', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('town_village', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('current_grade', models.CharField(max_length=10)),
                ('town_village', models.CharField(max_length=100)),
                ('country_of_origin', models.CharField(max_length=100)),
                ('date_of_intake', models.DateField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='project.parent')),
            ],
        ),
        migrations.CreateModel(
            name='AdvocacyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length_of_contact', models.DecimalField(decimal_places=2, max_digits=4)),
                ('description', models.TextField()),
                ('date_of_contact', models.DateField()),
                ('school_district', models.CharField(max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advocacy_sessions', to='project.student')),
            ],
        ),
        migrations.CreateModel(
            name='TutoringService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_contact', models.DateField()),
                ('location_of_contact', models.CharField(max_length=200)),
                ('session_focus', models.CharField(max_length=100)),
                ('activity', models.TextField()),
                ('length_of_session', models.DecimalField(decimal_places=2, max_digits=4)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoring_sessions', to='project.student')),
            ],
        ),
    ]
