# Generated by Django 5.1.1 on 2024-12-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_student_current_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='country_of_origin',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
