# Generated by Django 5.1.1 on 2025-05-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_parent_country_of_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email_address',
            field=models.EmailField(blank=True, default='None', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, default='None', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='country_of_origin',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
    ]
