# Generated by Django 5.1.1 on 2024-10-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0005_alter_image_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image_file',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image_url',
            field=models.URLField(blank=True),
        ),
    ]
